var unified = require('unified')
var parse = require('rehype-parse')
var format = require('rehype-format')
var document = require('rehype-document')
var stringify = require('rehype-stringify')
var reporter = require('vfile-reporter')
var toVfile = require('to-vfile')
var partials = require('../')

unified()
  .use(parse, { fragment: true })
  .use(stringify)
  .use(partials)
  .use(document, { title: 'Example' })
  .use(format)
  .process(toVfile.readSync('./index.html'), function (err, file) {
    console.error(reporter(err || file))
    console.log(String(file))
  })
